Adding ephemeral mode to birthdays and easy implementation for futures features
Croos3r/tar-le-bot-en-mieux pull request #7
Opened 2022-12-11 21:34 UTC by Croos3r

This PR sets the interaction replies of the birthdays commands to ephemeral mode, it also add an easy way to use them

2022-12-11 22:47 UTC, Snowy1803 requested changes

2022-12-11 22:47 UTC, Snowy1803 commented on src/utils/discordjs.ts
> +    private nextIsEphemeral: boolean
C'est degeulasse et en plus tu l'utilise jamais, c'est quoi ça ? feur

2022-12-11 22:49 UTC, Croos3r commented on src/utils/discordjs.ts
> +    private nextIsEphemeral: boolean
Bah si je l'utilise, ligne 43 et 47

2022-12-12 22:56 UTC, Snowy1803 commented on src/utils/discordjs.ts
> +    private nextIsEphemeral: boolean
les fonctions `nextEphemeral` et `nextNotEphemeral` sont utilisés où ?

2022-12-14 00:04 UTC, merged